version = 0.1

[default.deploy.parameters]
stack_name = "tcob-movies"
resolve_s3 = true
s3_prefix = "tcob-movies"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AllowedOrigin=\"https://tcob.com\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
